name: Pollito Chambeador

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: 'Ingresa tu nombre'
        required: true
        type: string

jobs:
  imprimir:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: |
          echo "El pollito más chambeador es: ${{ github.event.inputs.nombre }}"
